DROP TABLE IF EXISTS CITY;

CREATE TABLE CITY (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR, COUNTRY VARCHAR, POPULATION INT);

INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('San Francisco', 'US', 10000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('서울', 'KR', 20000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('일본', 'JP', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('부산', 'KR', 40000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('인천', 'KR', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('광주', 'KR', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('대전', 'KR', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('미국', 'US', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('알레스카', 'US', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('조지아', 'US', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('후쿠오카', 'JP', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('산주쿠', 'JP', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('제주도', 'KR', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('통영', 'KR', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('여수', 'KR', 30000);